In [27]:
import numpy as np

types of array's

In [28]:
arr1 = np.array([3,35,6,3,4,5])
arr1

array([ 3, 35,  6,  3,  4,  5])

In [29]:
# This is a multidimensional array
arr2 = np.array([[3,35,6,5],[6,4,34,7]])
arr2

array([[ 3, 35,  6,  5],
       [ 6,  4, 34,  7]])

In [ ]:
arr31 = np.zeros((3,5))
arr32 = np.zeros((3))
arr33 = np.zeros((0,3)) # this is empty array array([], shape=(4, 0), dtype=float64)
print(arr31)
print(arr32)
print(arr33)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0. 0. 0.]
[]


array([], shape=(0, 3), dtype=float64)

In [31]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
arr5 = np.identity(5)
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [35]:
arr6 = np.arange(11)# here it will give a result in array because numpy support arrays only
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr7 = np.linspace(11,20,7)
arr7

array([11. , 12.5, 14. , 15.5, 17. , 18.5, 20. ])

In [43]:
arr8 = arr6.copy()
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])