Properties and dimension

1.Shape
2.nDim
3.Size
4.Itemseze
5.Dtype
6.astype() 


In [44]:
import numpy as np

In [45]:
val = np.ones((3,5))
val

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
shape1 =  val.shape
shape1

(3, 5)

In [47]:
val2 = np.array([ [[34, 34], [34, 34], [34, 3] ],[ [34, 4],  [34, 4],  [34, 4] ]])
val2

array([[[34, 34],
        [34, 34],
        [34,  3]],

       [[34,  4],
        [34,  4],
        [34,  4]]])

In [48]:
shape2 = val2.shape
shape2  #(2, 3, 2)  (2 matrix, 3 rows, 2 column)

(2, 3, 2)

In [49]:
a= np.array([[[34,4],[4,4]],
              [[3,5],[5,6]], 
              [[3,4],[4,56]]])
aa = a.shape
print("Dimension is ",a.ndim)
aa

Dimension is  3


(3, 2, 2)

In [50]:
#val2 = np.array([ [[34, 34], [34, 34], [34, 3] ],[ [34, 4],  [34, 4],  [34, 4] ], dtype=np.float32])
size = val2.size
size

12

In [51]:
#itemsize :::  it will give a size according to size of each item like int: 4, float:8  but for 64 bit system int and float size are same 
# to change it { dtype = np.int32 }

itsize2 = val2.itemsize
itsize2

8

In [52]:
val2.dtype

dtype('int64')

In [53]:
val2.astype("float")  #here we can convert the datatype of numpy array
# it is used when cleaning data

array([[[34., 34.],
        [34., 34.],
        [34.,  3.]],

       [[34.,  4.],
        [34.,  4.],
        [34.,  4.]]])