In [4]:
import numpy as np

Indexing


Slicing

In [11]:
slic = np.arange(30).reshape(5,6)
slic

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [14]:
slic[1:4] # we will get a row as a slicing result

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [16]:
slic[-1] #negative slicing

array([24, 25, 26, 27, 28, 29])

In [18]:
slic[::-1] #Reverce

array([[24, 25, 26, 27, 28, 29],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [21]:
slic[:,3]

array([ 3,  9, 15, 21, 27])