In [2]:
import numpy as np

Indexing


Slicing

In [3]:
slic = np.arange(30).reshape(5,6)
slic

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [4]:
slic[1:4] # we will get a row as a slicing result

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
slic[-1] #negative slicing

array([24, 25, 26, 27, 28, 29])

In [6]:
slic[::1] #Reverce

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
slic[ : , 3:5]
#   rows, column      \\\row-all  , column -3 to 5

array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22],
       [27, 28]])