In [1]:
import numpy as np

Indexing


In [15]:
array = np.arange(25).reshape(5,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [3]:
array[[0, 3, 4]]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Slicing

In [4]:
slic = np.arange(30).reshape(5,6)
slic

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [5]:
slic[1:4] # we will get a row as a slicing result

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [6]:
slic[-1] #negative slicing

array([24, 25, 26, 27, 28, 29])

In [7]:
slic[::1] #Reverce

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [8]:
slic[ :, 3:5]
#   rows, column      \\\row-all  , column -3 to 5

array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22],
       [27, 28]])

In [9]:
slic[3:,3:]

array([[21, 22, 23],
       [27, 28, 29]])

Iteration


In [16]:
for i in slic:
    print(i)


for i in np.nditer(slic): # we git a single element printed  n-dimension iterator
    print(i)    

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
