Basic operation's

In [2]:
import numpy as np

In [3]:
oper1 = np.array([1,2,3,4,5,6])
oper2 = np.arange(4, 10)

In [4]:
oper1 - oper2

array([-3, -3, -3, -3, -3, -3])

In [5]:
oper1 * oper2 # vector multiplication 

array([ 4, 10, 18, 28, 40, 54])

In [6]:
oper1 * 2 #Scalar multiplication

array([ 2,  4,  6,  8, 10, 12])

In [7]:
oper1 > 3

array([False, False, False,  True,  True,  True])

Matrix Multiplication 


In [8]:
oper3 = np.arange(6).reshape(2,3)
oper4 = np.arange(6,12).reshape(3,2)
print(oper3,"\n\n")
print(oper4)

[[0 1 2]
 [3 4 5]] 


[[ 6  7]
 [ 8  9]
 [10 11]]


In [9]:
oper3 .dot(oper4)

array([[ 28,  31],
       [100, 112]])

In [10]:
oper4.max()

np.int64(11)

In [11]:
oper4.min(axis=1) #minimum of a each row

array([ 6,  8, 10])

In [12]:
oper4.min(axis=0) #minimum of a each column

array([6, 7])

In [13]:
oper4.sum()

np.int64(51)

In [14]:
oper4.sum(axis=0)# column addition

array([24, 27])

In [15]:
oper4.sum(axis=1)# row addition

array([13, 17, 21])

In [16]:
oper4.mean() 
oper4.mean(axis=0)

array([8., 9.])

In [17]:
np.mean(oper4) #np.float64(8.5)
np.median(oper4)

np.float64(8.5)

In [18]:
oper4.std()# this also has a axix

np.float64(1.707825127659933)

In [19]:
np.sin(oper4)#Trignometry

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [20]:
np.log(oper4)

array([[1.79175947, 1.94591015],
       [2.07944154, 2.19722458],
       [2.30258509, 2.39789527]])

In [ ]:
lis = ["l", "a"]
result = "".join(lis)
result

'la'