<h4>Reshaping the numpy array</h4>

In [1]:
import numpy as np

In [13]:
array = np.array([[3,5,3],[2,34,5],[23,4,5]])
array

array([[ 3,  5,  3],
       [ 2, 34,  5],
       [23,  4,  5]])

In [ ]:
# this will convert higher dimension in to 1D array

array.ravel()  # this will give 1d array
#or np.ravel(array)  
#object.method()      function--prefered to use
array.flatten()# this will give a copy of 1d array

array([ 3,  5,  3,  2, 34,  5, 23,  4,  5])

In [18]:
arr1 = np.array([ 3,  5,  3,  2, 34,  5, 23,  4,  5, 45])
arr1.reshape(2,5)


array([[ 3,  5,  3,  2, 34],
       [ 5, 23,  4,  5, 45]])

In [22]:
np.transpose(array)  # or array.transpose()

array([[ 3,  2, 23],
       [ 5, 34,  4],
       [ 3,  5,  5]])

In [26]:
arr2 = np.arange(6).reshape(2,3)
arr3 = np.arange(6, 12).reshape(2,3)
arr3

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
np.hstack((arr2, arr3)) # Horizontal stack ::: it joint the array column wise

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [31]:
np.vstack((arr2,arr3)) #vertical stack ::: it joint the array in row wise

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
    #    [ 3,  5,  3],
    #    [ 2, 34,  5],
    #    [23,  4,  5]

np.hsplit(array,3)    
    

[array([[ 3],
        [ 2],
        [23]]),
 array([[ 5],
        [34],
        [ 4]]),
 array([[3],
        [5],
        [5]])]

In [33]:
np.vsplit(array,3)

[array([[3, 5, 3]]), array([[ 2, 34,  5]]), array([[23,  4,  5]])]