<h3> Indexing with boolean array</h3>

In [1]:
import numpy as np

In [2]:
array = np.random.randint(low=1, high=100, size=20).reshape(4, 5)
array

array([[ 2, 14, 92, 71, 25],
       [25, 56,  2,  8, 58],
       [56, 75, 95, 19, 27],
       [24, 25, 85, 52, 36]], dtype=int32)

In [3]:
array > 50

array([[False, False,  True,  True, False],
       [False,  True, False, False,  True],
       [ True,  True,  True, False, False],
       [False, False,  True,  True, False]])

In [4]:
array[array > 50]

array([92, 71, 56, 58, 56, 75, 95, 85, 52], dtype=int32)

In [7]:
array[(array>50) & (array%2 ==0)] # we use a '&' and because this operation is mading using bolean balue

array([92, 56, 58, 56, 52], dtype=int32)

In [9]:
array[(array>50) & (array%2 ==0)] = 0
array  # making a matrix value as a zero

array([[ 2, 14,  0, 71, 25],
       [25,  0,  2,  8,  0],
       [ 0, 75, 95, 19, 27],
       [24, 25, 85,  0, 36]], dtype=int32)