In [1]:
import numpy as np

<h1>Broadcastiong </h1>

In [3]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
arr2 = np.array([[34],[34],[56]])
arr2

array([[34],
       [34],
       [56]])

In [ ]:
arr1 + arr2 #element still perform operation if the size differe's 

array([[34, 35, 36],
       [37, 38, 39],
       [62, 63, 64]])