In [1]:
import numpy as np

<h1>Broadcastiong </h1>

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
arr2 = np.array([[34],[34],[56]])
arr2

array([[34],
       [34],
       [56]])

In [4]:
arr1 + arr2 #element still perform operation if the size differe's 

array([[34, 35, 36],
       [37, 38, 39],
       [62, 63, 64]])

In [8]:
# 5. Broadcast a 1D array of shape (3,) to a 2D array of shape (3,3)
arr = np.array([1, 2, 3]) 
val_arr = np.broadcast_to(arr, (6,3))
val_arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])