<h2>Readme Topics</h2>

📌 Array Creation</br>
np.array()</br>
np.zeros()</br>
np.ones()</br>
np.empty()</br>
np.arange()</br>
np.linspace()</br>
np.eye() (identity matrix)</br>
np.full()</br>
np.random.rand(), np.random.randn(), np.random.randint()

In [1]:
import numpy as np

In [ ]:
# numpy.empty(shape, dtype=float, order='C' or 'f')
np.empty((3,5), order='f')

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 2.66023306e-312]])

In [4]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.identity(3)   #this will give a identity matrix of equal rows and column
np.eye(3,5 ,k=2) # this is flexible we can shift the rows and column with identiy

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
# np.full( shape , fill_value , dtype ) :: here we are creating a matrix with our required value in a matrix
np.full((3,3),78)

array([[78, 78, 78],
       [78, 78, 78],
       [78, 78, 78]])

In [ ]:
# Random thing
# generates niform distribution between 0 and 1
np.random.rand()  #0.9363802912698569
np.random.rand(3,5)

array([[0.63089861, 0.98941463, 0.09686127, 0.07728317, 0.57335301],
       [0.14051121, 0.92682619, 0.48889775, 0.46028793, 0.25338169],
       [0.09876413, 0.89996475, 0.28325531, 0.4904556 , 0.44502177]])

In [24]:
#generates standard normanl distribution(BELL CURVE), mean=0, std=1
np.random.randn()

0.3096429611887318

In [35]:
np.random.randint(11,53)    #single value in between 1-3
np.random.randint(5)        #single value in between 0-5
np.random.randint(1,10,3)   #3 value in between 1-10
np.random.randint(10,50,(3,4))

array([[24, 46, 31, 39],
       [49, 16, 48, 24],
       [26, 41, 48, 48]], dtype=int32)

📌 Array Manipulation<br>
np.reshape()<br>
np.transpose() or .T<br>
np.concatenate()<br>
np.vstack(), np.hstack()<br>
np.split(), np.hsplit(), np.vsplit(), np.array_split()<br>
np.squeeze(), np.expand_dims()<br>

