<h2>Readme Topics</h2>

📌 Array Creation</br>
np.array()</br>
np.zeros()</br>
np.ones()</br>
np.empty()</br>
np.arange()</br>
np.linspace()</br>
np.eye() (identity matrix)</br>
np.full()</br>
np.random.rand(), np.random.randn(), np.random.randint()

In [6]:
import numpy as np

In [7]:
# numpy.empty(shape, dtype=float, order='C' or 'f')
np.empty((3,5), order='f')

array([[0.e+000, 0.e+000, 0.e+000, 0.e+000, 0.e+000],
       [0.e+000, 0.e+000, 0.e+000, 0.e+000, 0.e+000],
       [0.e+000, 0.e+000, 0.e+000, 0.e+000, 6.e-322]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.identity(3)   #this will give a identity matrix of equal rows and column
np.eye(3,5 ,k=2) # this is flexible we can shift the rows and column with identiy

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
# np.full( shape , fill_value , dtype ) :: here we are creating a matrix with our required value in a matrix
np.full((3,3),78)

array([[78, 78, 78],
       [78, 78, 78],
       [78, 78, 78]])

In [11]:
# Random thing
# generates niform distribution between 0 and 1
np.random.rand()  #0.9363802912698569
np.random.rand(3,5)

array([[0.31512805, 0.279898  , 0.34230944, 0.42086375, 0.11358752],
       [0.00301042, 0.46047711, 0.65473639, 0.54572574, 0.16871914],
       [0.44557394, 0.54910956, 0.61215147, 0.68462047, 0.56995638]])

In [12]:
#generates standard normanl distribution(BELL CURVE), mean=0, std=1
np.random.randn()

2.0928323227176606

In [13]:
np.random.randint(11,53)    #single value in between 1-3
np.random.randint(5)        #single value in between 0-5
np.random.randint(1,10,3)   #3 value in between 1-10
np.random.randint(10,50,(3,4))

array([[15, 40, 48, 11],
       [12, 20, 49, 33],
       [35, 38, 48, 11]], dtype=int32)

📌 Array Manipulation<br>
np.reshape()<br>
np.transpose() or .T<br>
np.concatenate()<br>
np.vstack(), np.hstack()<br>
np.split(), np.hsplit(), np.vsplit(), np.array_split()<br>
np.squeeze(), np.expand_dims()<br>



In [14]:
array = np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<h4>Transpose</h4>

In [15]:
array.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [16]:
b = np.arange(24).reshape(2, 3, 4)
print(b)
print(b.shape)   # (2, 3, 4)

# Reorder dimensions (swap axis 0 and 1)
print(b.transpose(1, 0, 2).shape)  # (3, 2, 4)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
(3, 2, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
arra = np.array([[[2,3,54,4],[2,3,4,5]],
                 [[4,56,75,43],[3,4,56,6]]
                                       ])
arra.shape #(2, 2, 4) (depth, row, column)
arra.transpose(0,2,1) # this will specify the index of the shape 

array([[[ 2,  2],
        [ 3,  3],
        [54,  4],
        [ 4,  5]],

       [[ 4,  3],
        [56,  4],
        [75, 56],
        [43,  6]]])

In [ ]:
array1 = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
array2 = np.array([[[10, 11], [12, 13]], [[14, 15], [16, 17]]])

print(np.concatenate((array1, array2), axis=0),"\n\n")
# Adds new blocks along the first axis

print(np.concatenate((array1, array2), axis=1))
# Merges along the second axis (rows)

print(np.concatenate((array1, array2), axis=2))
# Merges along the third axis (depth)


[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[10 11]
  [12 13]]

 [[14 15]
  [16 17]]] 


[[[ 0  1]
  [ 2  3]
  [10 11]
  [12 13]]

 [[ 4  5]
  [ 6  7]
  [14 15]
  [16 17]]]
[[[ 0  1 10 11]
  [ 2  3 12 13]]

 [[ 4  5 14 15]
  [ 6  7 16 17]]]
